# 注意!!!!打包上線流程用，不要修改/刪除這個文件!!!!!

trigger:
  - none

pr: none

resources:
  repositories:
    - repository: devops
      type: github
      endpoint: MKTFEGitHub
      name: benjilai008/devops-k8s
      ref: main

variables:
  prod: 'f1'
  lang: 'hi'
  platform: 'static'
  sourceCodeFolderName: 'F1-M5-STATIC'
  commitHash: $(Build.SourceVersion)
  sourcesDirectory: $(Build.SourcesDirectory)
  buildNumber: $(Build.BuildNumber)
  acrServConn: 'MKTFEACR'

pool:
  vmImage: 'ubuntu-latest'
  environment: $(serverBranch)

stages:
  - template: azp/html/pack/pack-template-static.yml@devops
    parameters:
      prod: $(prod)
      lang: $(lang)
      platform: $(platform)
      sourceCodeFolderName: $(sourceCodeFolderName)
      commitHash: $(commitHash)
      sourcesDirectory: $(sourcesDirectory)
      buildNumber: $(buildNumber)
      acrServConn: $(acrServConn)
